##
## This file was generated by Google::ProtocolBuffers (0.08)
## on Sun Oct 23 15:58:37 2011
##      
use strict;
use warnings;
use Google::ProtocolBuffers;
{       
    unless (Detail->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Detail',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'DeviceDoc', 
                    'deviceDoc', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (RequestContext->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'RequestContext',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'Detail', 
                    'deviceDetail', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (AppsResponse->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'AppsResponse',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'RequestContext', 
                    'payload', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (AppDetail->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'AppDetail',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'majorCode', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_INT32(), 
                    'versionCode', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (DocumentDetail->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'DocumentDetail',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'AppDetail', 
                    'appDetail', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (DeviceDoc->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'DeviceDoc',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    'DocumentDetail', 
                    'documentDetail', 9, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

}
1;
